-- CREATE TABLE users (
--                       ID INTEGER NOT NULL AUTO_INCREMENT,
--                       username VARCHAR(255) NOT NULL,
--                       password VARCHAR(255) NOT NULL,
--                       PRIMARY KEY(ID)
-- );